---
deployment:
  tasks:
    # Git pulls files to /home/snusegypt/repositories/snusegypt2026
    # Set correct permissions only
    - chmod -R 755 /home/snusegypt/repositories/snusegypt2026/storage
    - chmod -R 755 /home/snusegypt/repositories/snusegypt2026/bootstrap/cache
    - chmod -R 755 /home/snusegypt/repositories/snusegypt2026/public
