<?php

namespace Database\Seeders;

use App\Models\Admin\MenuBuilder;
use Illuminate\Database\Seeder;

class MenuBuilderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        MenuBuilder::where('id', '>', '0')->delete();
        MenuBuilder::insertOrIgnore([
            'menu' => '[
                    {
                        "id": 1628672836150,
                        "link": "",
                        "name": [
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home",
                            "Home"
                        ],
                        "page": "/",
                        "type": "page",
                        "exlink": "",
                        "product": "",
                        "category": "",
                        "children": [],
                        "contentpage": "",
                        "language_id": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31
                        ]
                    },
                    {
                        "id": 1628672997563,
                        "link": "",
                        "name": [
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop",
                            "Shop"
                        ],
                        "page": "/shop",
                        "type": "page",
                        "exlink": "",
                        "product": "",
                        "category": "",
                        "children": [],
                        "contentpage": "",
                        "language_id": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31
                        ]
                    },
                    {
                        "id": 1628672976637,
                        "link": "",
                        "name": [
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog",
                            "Blog"
                        ],
                        "page": "/blog",
                        "type": "page",
                        "exlink": "",
                        "product": "",
                        "category": "",
                        "children": [],
                        "contentpage": "",
                        "language_id": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31
                        ]
                    },
                    {
                        "id": 1628672935413,
                        "link": "",
                        "name": [
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us",
                            "Contact Us"
                        ],
                        "page": "/contact-us",
                        "type": "page",
                        "exlink": "",
                        "product": "",
                        "category": "",
                        "children": [],
                        "contentpage": "",
                        "language_id": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31
                        ]
                    }
                    
            ]',

        ]);

    }
}
